# Generated by Django 2.2.7 on 2019-12-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voldemath', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='makale_tag',
            field=models.CharField(auto_created=True, blank=True, default='<django.db.models.fields.related.ForeignKey>', max_length=250, null=True),
        ),
    ]
