# Generated by Django 2.2.7 on 2019-12-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voldemath', '0002_makale_makale_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makale',
            name='makale_tag',
        ),
        migrations.AddField(
            model_name='makale',
            name='makale_tagg',
            field=models.CharField(blank=True, default='<django.db.models.fields.related.ForeignKey>', max_length=250, null=True),
        ),
    ]
