# Generated by Django 2.2.7 on 2019-12-05 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voldemath', '0003_auto_20191205_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makale',
            name='makale_tagg',
        ),
    ]
