# Generated by Django 2.2.7 on 2019-12-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voldemath', '0004_remove_makale_makale_tagg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daha_once_makaleci_istegi_yapti_mi',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='daha_once_paylasimci_istegi_yapti_mi',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
