# Generated by Django 2.2.7 on 2019-12-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voldemath', '0005_auto_20191213_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='okul_no',
        ),
        migrations.AddField(
            model_name='user',
            name='hesap_aktif_mi',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
