# Generated by Django 2.2.7 on 2019-12-23 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voldemath', '0008_auto_20191223_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makale',
            name='yazarin_bagli_oldugu_yer',
        ),
    ]
