# Generated by Django 2.2.7 on 2019-12-23 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Voldemath', '0009_remove_makale_yazarin_bagli_oldugu_yer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isOfficer',
        ),
        migrations.AddField(
            model_name='makale',
            name='makaleyi_paylasan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Voldemath.User'),
            preserve_default=False,
        ),
    ]
